apiVersion: shipwright.io/v1alpha1
kind: Build
metadata:
  name: kaniko-build
spec:
  source:
    url: https://github.com/imjasonh/shipwright-example
  dockerfile: Dockerfile
  strategy:
    name: kaniko
    kind: ClusterBuildStrategy
  output:
    image: quay.io/imjasonh/shipwright
    credentials:
      name: push-secret 
