apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: buildpack-java-build
spec:
  source:
    type: Git
    git: 
      url: https://github.com/jkhelil/shipwright-example.git
    contextDir: hello-world-spring-boot
  strategy:
    name: buildpacks-v3
    kind: ClusterBuildStrategy
  output:
    image: quay.io/jkhelil/shipwright-example:latest
    pushSecret: push-secret

